version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: eventbridge-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: eventbridge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
